import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "ESG Works",
  // description: "Generated by create next app",
  icons: {
    icon: "../logo-colored.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          backgroundColor: "white",
          flexDirection: "column",
          // justifyContent: "center",
          // alignItems: "center",
          padding: 0,
          margin: 0,
        }}
      >
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <div>
          <Provider>
            {children}
            <Toaster />
          </Provider>
        </div>
      </body>
    </html>
  );
}
